spring:
    application:
        name: userservice
    jpa:
        hibernate:
            ddl-auto: ${SPRING_JPA_HIBERNATE_DLL_AUTO}
        show-sql: true

    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}